// <auto-generated />
namespace Cookbook.Database
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ImageForRecipe : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ImageForRecipe));
        
        string IMigrationMetadata.Id
        {
            get { return "201512131450056_ImageForRecipe"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
