// <auto-generated />
namespace Cookbook.Database
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DescriptionForRecipe : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DescriptionForRecipe));
        
        string IMigrationMetadata.Id
        {
            get { return "201601041121451_DescriptionForRecipe"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
